# This file is a template, and might need editing before it works on your project.
variables:
  RELEASE: ""
  DOCKERHOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

docker-build-buildx:
  # Official docker image.
  image: registry.gitlab.com/dedyms/docker-with-buildx:0.5.1
  stage: build
  services:
    - docker:dind
  before_script:
    - export RELEASE="alpine"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  script:
    #- docker build --pull -t "$CI_REGISTRY_IMAGE:$DATE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE" .
    #- docker push "$CI_REGISTRY_IMAGE:$DATE"
    #- docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE"
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" .
  only:
    refs:
      - master
      - schedules
    changes:
      - Dockerfile
      - .gitlab-ci.yml
